[project]
name = "demo-5-1-attach-toolbox"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "agent-framework",
    "agent-framework-foundry",
    "azure-identity",
    "python-dotenv",
]

[[tool.uv.index]]
name = "internal"
url = "https://packagefeedproxy.microsoft.io/pypi/simple/"
